/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectohosting;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zarza
 */
public class JF_admin extends javax.swing.JFrame {

    /**
     * Creates new form JF_admin
     */
    public JF_admin() {
        initComponents();
        actualizarTablaClientes("");
        cargaUsuario();
        
    }
public final void actualizarTablaClientes(String valor){
        DefaultTableModel modelo = (DefaultTableModel) JTclientes.getModel();
        String sql;
        String[] registro = new String[5];
        
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();
        sql = "SELECT nombre, apellidos, correo, DNI, fechaAlta FROM clientes "
                + "WHERE CONCAT (nombre, ' ', apellidos, ' ', correo, ' ', DNI, ' ', fechaAlta) LIKE '%"+valor+"%'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                registro[0] = rs.getString("nombre");
                registro[1] = rs.getString("apellidos");
                registro[2] = rs.getString("correo");
                registro[3] = rs.getString("DNI");
                registro[4] = rs.getString("fechaAlta");
                
                modelo.addRow(registro);
            }
            JTclientes.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

private void cargaUsuario() {
        try{
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();
        Statement sent = cn.createStatement();
        ResultSet rs = sent.executeQuery("SELECT nombre, apellidos FROM clientes");
        
        
        while( rs.next()){
            String nombreCompleto = rs.getString("nombre") + " " + rs.getString("apellidos");
            this.JCpropietario.addItem(nombreCompleto);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLpaneldeadministracion = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPclientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTclientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        JTapellidosCliente = new javax.swing.JTextField();
        JTcorreoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTnombreCliente = new javax.swing.JTextField();
        JTdniCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JBbaja_cliente = new javax.swing.JButton();
        JBalta_cliente = new javax.swing.JButton();
        JPdominios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        paneldominio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JTdominio = new javax.swing.JTextField();
        JCpropietario = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        JBaltaDominio = new javax.swing.JButton();
        JBbajaDominio = new javax.swing.JButton();
        JPhostings = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLpaneldeadministracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLpaneldeadministracion.setText("Panel de administración");

        JTclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Correo", "DNI", "Fecha de alta"
            }
        ));
        jScrollPane1.setViewportView(JTclientes);

        jLabel3.setText("Correo:");

        jLabel2.setText("Apellidos:");

        JTnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnombreClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("DNI:");

        jLabel1.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTdniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTcorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTapellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JTapellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTcorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTdniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21))
        );

        JBbaja_cliente.setBackground(new java.awt.Color(255, 153, 153));
        JBbaja_cliente.setText("Dar de baja");
        JBbaja_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbaja_clienteActionPerformed(evt);
            }
        });

        JBalta_cliente.setBackground(new java.awt.Color(153, 255, 153));
        JBalta_cliente.setText("Dar de alta");
        JBalta_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalta_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPclientesLayout = new javax.swing.GroupLayout(JPclientes);
        JPclientes.setLayout(JPclientesLayout);
        JPclientesLayout.setHorizontalGroup(
            JPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPclientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPclientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(JPclientesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(JPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBalta_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBbaja_cliente))
                        .addGap(64, 64, 64))))
        );
        JPclientesLayout.setVerticalGroup(
            JPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPclientesLayout.createSequentialGroup()
                .addGroup(JPclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPclientesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPclientesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(JBalta_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBbaja_cliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Clientes", JPclientes);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dominio", "Precio", "Fecha de alta", "Fecha de baja", "Propietario"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(4).setMinWidth(200);
        }

        jLabel5.setText("Dominio:");

        JTdominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTdominioActionPerformed(evt);
            }
        });

        JCpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCpropietarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Propietario:");

        javax.swing.GroupLayout paneldominioLayout = new javax.swing.GroupLayout(paneldominio);
        paneldominio.setLayout(paneldominioLayout);
        paneldominioLayout.setHorizontalGroup(
            paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldominioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTdominio)
                    .addComponent(JCpropietario, 0, 183, Short.MAX_VALUE))
                .addGap(0, 162, Short.MAX_VALUE))
        );
        paneldominioLayout.setVerticalGroup(
            paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldominioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTdominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(paneldominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JCpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        JBaltaDominio.setBackground(new java.awt.Color(153, 255, 153));
        JBaltaDominio.setText("Dar de alta");
        JBaltaDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBaltaDominioActionPerformed(evt);
            }
        });

        JBbajaDominio.setBackground(new java.awt.Color(255, 153, 153));
        JBbajaDominio.setText("Dar de baja");

        javax.swing.GroupLayout JPdominiosLayout = new javax.swing.GroupLayout(JPdominios);
        JPdominios.setLayout(JPdominiosLayout);
        JPdominiosLayout.setHorizontalGroup(
            JPdominiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPdominiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPdominiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(JPdominiosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(paneldominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JPdominiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBbajaDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBaltaDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPdominiosLayout.setVerticalGroup(
            JPdominiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPdominiosLayout.createSequentialGroup()
                .addGroup(JPdominiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPdominiosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(JBaltaDominio)
                        .addGap(18, 18, 18)
                        .addComponent(JBbajaDominio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPdominiosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paneldominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dominios", JPdominios);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout JPhostingsLayout = new javax.swing.GroupLayout(JPhostings);
        JPhostings.setLayout(JPhostingsLayout);
        JPhostingsLayout.setHorizontalGroup(
            JPhostingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPhostingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPhostingsLayout.setVerticalGroup(
            JPhostingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPhostingsLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hostings", JPhostings);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLpaneldeadministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLpaneldeadministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnombreClienteActionPerformed

    private void JBbaja_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbaja_clienteActionPerformed
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();

        int fila = JTclientes.getSelectedRow();
        Object dni = JTclientes.getValueAt(fila,3).toString();
        String sql = "DELETE FROM clientes WHERE DNI='"+dni+"'";

        try{
            PreparedStatement pst = cn.prepareStatement(sql);

            pst.executeUpdate();

            //actualiza la tabla en el momento de añadir un nuevo participante
            ((DefaultTableModel)JTclientes.getModel()).setRowCount(0);
            actualizarTablaClientes("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_JBbaja_clienteActionPerformed

    private void JBalta_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalta_clienteActionPerformed
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();
        Date fechaActual = new Date();
        String fechaActualFormat = new SimpleDateFormat("yyyy-MM-dd").format(fechaActual);

        String nombre, apellidos, correo, DNI, fechaAlta;
        nombre = JTnombreCliente.getText();
        apellidos = JTapellidosCliente.getText();
        correo = JTcorreoCliente.getText();
        DNI = JTdniCliente.getText();
        fechaAlta = fechaActualFormat;

        String sql = "INSERT INTO clientes (nombre, apellidos, correo, DNI, fechaAlta) VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, apellidos);
            pst.setString(3, correo);
            pst.setString(4, DNI);
            pst.setString(5, fechaAlta);

            int n = pst.executeUpdate();

            //actualiza la tabla en el momento de añadir un nuevo participante
            ((DefaultTableModel)JTclientes.getModel()).setRowCount(0);
            actualizarTablaClientes("");
            JTnombreCliente.setText("");
            JTapellidosCliente.setText("");
            JTdniCliente.setText("");
            JTcorreoCliente.setText("");
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_JBalta_clienteActionPerformed

    private void JTdominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTdominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdominioActionPerformed

    private void JCpropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCpropietarioActionPerformed
      
    }//GEN-LAST:event_JCpropietarioActionPerformed

    private void JBaltaDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBaltaDominioActionPerformed
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();
        Date fechaActual = new Date();
        String fechaActualFormat = new SimpleDateFormat("yyyy-MM-dd").format(fechaActual);

        String nombre, apellidos, correo, DNI, fechaAlta;
        nombre = JTnombreCliente.getText();
        apellidos = JTapellidosCliente.getText();
        correo = JTcorreoCliente.getText();
        DNI = JTdniCliente.getText();
        fechaAlta = fechaActualFormat;

        String sql = "INSERT INTO clientes (nombre, apellidos, correo, DNI, fechaAlta) VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, apellidos);
            pst.setString(3, correo);
            pst.setString(4, DNI);
            pst.setString(5, fechaAlta);

            int n = pst.executeUpdate();

            //actualiza la tabla en el momento de añadir un nuevo participante
            ((DefaultTableModel)JTclientes.getModel()).setRowCount(0);
            actualizarTablaClientes("");
            JTnombreCliente.setText("");
            JTapellidosCliente.setText("");
            JTdniCliente.setText("");
            JTcorreoCliente.setText("");
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_JBaltaDominioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JF_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBaltaDominio;
    private javax.swing.JButton JBalta_cliente;
    private javax.swing.JButton JBbajaDominio;
    private javax.swing.JButton JBbaja_cliente;
    private javax.swing.JComboBox JCpropietario;
    private javax.swing.JLabel JLpaneldeadministracion;
    private javax.swing.JPanel JPclientes;
    private javax.swing.JPanel JPdominios;
    private javax.swing.JPanel JPhostings;
    private javax.swing.JTextField JTapellidosCliente;
    private javax.swing.JTable JTclientes;
    private javax.swing.JTextField JTcorreoCliente;
    private javax.swing.JTextField JTdniCliente;
    private javax.swing.JTextField JTdominio;
    private javax.swing.JTextField JTnombreCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel paneldominio;
    // End of variables declaration//GEN-END:variables

    
}
