/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectohosting;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Zarza
 */
public class JF_whois extends javax.swing.JFrame {

    /**
     * Creates new form JF_Whois
     */
    public JF_whois() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTwhois = new javax.swing.JTextField();
        JTbuscar = new javax.swing.JButton();
        JTvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("WHOIS");

        JTbuscar.setText("Buscar");
        JTbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbuscarActionPerformed(evt);
            }
        });

        JTvolver.setText("Volver");
        JTvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(JTbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(JTvolver))
                    .addComponent(JTwhois, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(JTwhois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTbuscar)
                    .addComponent(JTvolver))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbuscarActionPerformed
       String dominio = JTwhois.getText();
       
        String sql;
        String[] registro = new String[4];
        
        Conectar mysql = new Conectar();
        Connection cn = mysql.conexSQL();
        sql = "SELECT propietario, dominio, fechaAlta, fechaBaja FROM dominios "
                + "WHERE dominio LIKE '%"+dominio+"%'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                registro[0] = rs.getString("dominio");
                registro[1] = rs.getString("fechaAlta");
                registro[2] = rs.getString("fechaBaja");
                registro[3] = rs.getString("propietario");
            } 
            if(registro[0]==null)JOptionPane.showMessageDialog(null,"El dominio "+dominio+" está disponible para su registro.");
            else JOptionPane.showMessageDialog(null,"El dominio "+dominio+" no está disponible. \n\nDATOS WHOIS: \n\nRegistrador: "+registro[3]
                                                              +"\nFecha de alta: "+registro[1]+"\nFecha de caducidad: "+registro[2]);
           
            
          
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    
    }//GEN-LAST:event_JTbuscarActionPerformed

    private void JTvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTvolverActionPerformed
        this.dispose();
        new JF_login().setVisible(true);    
    }//GEN-LAST:event_JTvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_whois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_whois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_whois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_whois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_whois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTbuscar;
    private javax.swing.JButton JTvolver;
    private javax.swing.JTextField JTwhois;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
